# Generated by Django 2.0.2 on 2018-04-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='audio URL'),
        ),
        migrations.AddField(
            model_name='question',
            name='img_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='image URL'),
        ),
        migrations.AddField(
            model_name='question',
            name='other_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='other URL'),
        ),
        migrations.AddField(
            model_name='question',
            name='video_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='video URL'),
        ),
        migrations.AlterField(
            model_name='question',
            name='labels',
            field=models.ManyToManyField(blank=True, to='tests.Label', verbose_name='labels'),
        ),
    ]
