# Generated by Django 2.0.2 on 2018-04-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_test_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='correct',
            field=models.NullBooleanField(),
        ),
    ]
