# Generated by Django 2.0.2 on 2018-04-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_auto_20180416_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='automatic_start',
            field=models.BooleanField(default=False, verbose_name='should test start automatically'),
        ),
    ]
