# Generated by Django 2.0.2 on 2018-04-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_test_automatic_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='accessible_by',
            field=models.CharField(choices=[('anyone', 'Anyone'), ('invite', 'Invite')], default='anyone', help_text='Who can pass this test?', max_length=50, verbose_name='accessible by'),
        ),
        migrations.AddField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=50, verbose_name='status'),
        ),
    ]
