# Generated by Django 2.0.2 on 2018-04-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_auto_20180422_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start time'),
        ),
    ]
