# Generated by Django 2.0.2 on 2018-04-24 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_auto_20180423_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='manual_check',
            field=models.BooleanField(default=False, verbose_name='defines whether answer to this question should be manually approved'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.Question', verbose_name='questions'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='tests.Question', verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to=settings.AUTH_USER_MODEL, verbose_name='student'),
        ),
    ]
