# Generated by Django 2.0.2 on 2018-04-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_auto_20180424_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('requires_review', 'Required review'), ('done', 'Done')], default='new', max_length=20, verbose_name='status'),
        ),
    ]
