# Generated by Django 2.0.2 on 2018-04-25 16:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0014_auto_20180424_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='end_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 25, 16, 18, 20, 349685, tzinfo=utc), verbose_name='end at'),
            preserve_default=False,
        ),
    ]
