# Generated by Django 2.0.2 on 2018-02-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_visited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
